 http://localhost:2099/data

###

GET http://localhost:2099/data/1

###

POST http://localhost:2099/data HTTP/1.1
content-type: application/json

{
      "nome":"Mauricio",
      "sobrenome":"Bezerra",
      "telefone":"11-999999999",
      "data":"15/11/2021",
      "mensagem":"Olá! Você está recebendo uma mensagem de teste",
      "hora":"14:07"
}

###

PUT http://localhost:2099/data/3 HTTP/1.1
content-type: application/json

{
      "nome":"Genesio",
      "sobrenome":"Filho",
      "telefone":"11-999999999",
      "data":"15/11/2021",
      "mensagem":"Olá! Você está recebendo uma mensagem de teste",
      "hora":"14:07"
}

###

DELETE http://localhost:2099/data/5